- name: Provision all VMs
  hosts: all
  become: yes
  roles:
    - common

- name: Install k3s on dev
  hosts: dev
  become: yes
  roles:
    - k3s_server
    - vault
    - argocd
    - sonarqube

- name: Install k3s on prod
  hosts: prod
  become: yes
  roles:
    - k3s_server